### PR TITLE
snap: add hcitool

### PR DESCRIPTION
**Pull request by poussa**
Add another BLE tool to the snap.

### CODE REVIEW

**Comment by poussa** [comment]
@nagineni @gvancuts

**Comment by gvancuts** [comment]
This looks good to me. One more generic question, what is using those tools?

**Comment by poussa** [comment]
With hcitool you can scan e.g., the BLE devices and connect to them. Next, we'll add some scripts which does this more easily.

**Comment by nagineni** [comment]
LGTM

**Pull request merged**
